FROM cgr.dev/chainguard/wolfi-base:latest

USER root

RUN apk add make git python3

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

RUN python -m ensurepip && pip3 install uv

RUN mkdir -p /home/user/.local/bin && \
chown -R 1000:0 /home/user && \
chown -R 1000:0 /usr/local

USER 1000

ENV HOME=/home/user
ENV PATH="/home/user/.local/bin:$PATH"
