FROM cgr.dev/chainguard/wolfi-base:latest

USER root

RUN apk add make git python3

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

RUN python -m ensurepip && pip3 install uv

USER 1000
