FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

COPY src ./src
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev --production --ignore-scripts

COPY --from=builder /app/build ./build

RUN chmod +x build/index.js

ENV TRANSPORT=http
ENV PORT=8098

CMD ["node", "build/index.js"]