FROM cgr.dev/chainguard/wolfi-base:latest

USER root

RUN apk add make git nodejs npm pnpm

RUN npm install -g npm

RUN mkdir -p /home/user/.npm && chown -R 1000:1000 "/home/user/.npm"

# Setup chrome for things like Playwright
RUN mkdir -p /opt/google/chrome && \
    apk add chromium && \
    ln -sf /usr/bin/chromium-browser /opt/google/chrome/chrome

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

USER 1000
