FROM ghcr.io/github/github-mcp-server as binary

FROM ghcr.io/obot-platform/mcp-images-phat:main

COPY --from=binary /server/github-mcp-server .

USER root

RUN cat > nanobot.yaml <<'EOF'
publish:
  mcpServers: [server]

mcpServers:
  server:
    command: ./github-mcp-server
    args: [stdio]
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
EOF

RUN chown 1000 nanobot.yaml

ENTRYPOINT ["nanobot"]

CMD ["run", "--listen-address", ":8099", "./nanobot.yaml"]

USER 1000
